apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vwks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vwks
    app.kubernetes.io/part-of: tkrw-pr712-0075-0065-app
  name: devfile-sample-vwks
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vwks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vwks
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-vwks@sha256:d577070f1eeb0333148fd307e3c42f5c1f96171772312faeb1d65abac9a0b5d6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
